### ISSUE TITLE
Pr 템플릿을 만드세요

### ISSUE THREAD

**Issue by stygj** [KathleenJung/boardproject#4]
https://2jinishappy.tistory.com/m/337

**Comment by KathleenJung** [comment]
https://github.com/KathleenJung/boardproject/blob/main/.github/pull_request_template.md
![image](https://github.com/KathleenJung/boardproject/assets/85939045/22622744-2691-4824-a6de-ab889a10f833)
![image](https://github.com/KathleenJung/boardproject/assets/85939045/84710d06-17b7-4f74-b8e1-997ba15cd00e)
